CREATE TABLE [dbo].[Address]
(
	[Id] INT NOT NULL CONSTRAINT [PK_Address] PRIMARY KEY IDENTITY(1,1),
	[UserId] INT NOT NULL CONSTRAINT [FK_Address_User] FOREIGN KEY REFERENCES [dbo].[User](Id),
	[Street] NVARCHAR(250) NOT NULL,
	[StreetNumber] NVARCHAR(25) NOT NULL,
	[Floor] NUMERIC(3) NULL,
	[Office] NUMERIC(5) NULL,
	[City] NVARCHAR(250) NOT NULL,
	[PostalCode] NVARCHAR(25) NOT NULL
)
