CREATE TABLE [dbo].[Adress]
(
	[Id] INT NOT NULL CONSTRAINT [PK_Adress] PRIMARY KEY IDENTITY(1,1),
	[Street] NVARCHAR(250) NOT NULL,
	[StreetNumber] NVARCHAR(25) NOT NULL,
	[Floor] NUMERIC(3) NULL,
	[Office] NUMERIC(5) NULL,
	[City] NVARCHAR(250) NOT NULL,
	[PostalCode] NVARCHAR(25) NOT NULL
)
