CREATE TABLE [dbo].[Store]
(
	[Id] INT NOT NULL CONSTRAINT [PK_Store] PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(250) NOT NULL,
	[Description] NVARCHAR(500) NULL,
	[Location] NVARCHAR(500) NOT NULL
)
