CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL CONSTRAINT [PK_User] PRIMARY KEY IDENTITY(1,1),
	[UserName] NVARCHAR(50) NOT NULL CONSTRAINT [UK_UserName] UNIQUE,
	[Password] NVARCHAR(64) NOT NULL,
	[Name] NVARCHAR(50) NOT NULL, 
	[LastName] NVARCHAR(50) NOT NULL,
	[Email] NVARCHAR(100) NOT NULL CONSTRAINT [UK_UserEmail] UNIQUE,
	[Phone] NVARCHAR(25) NOT NULL CONSTRAINT [UK_UserPhone] UNIQUE,
	[ProfileId] INT NOT NULL CONSTRAINT [FK_User_Profile] FOREIGN KEY REFERENCES [dbo].[Profile](Id)
)