//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAdress
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int AdressId { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Adress Adress { get; set; }
        public virtual User User { get; set; }
    }
}
