CREATE TABLE [dbo].[Purchase]
(
	[Id] INT NOT NULL CONSTRAINT [PK_PurchaseId] PRIMARY KEY IDENTITY(1,1),
	[Total] INT NOT NULL,
	[Client] INT NOT NULL CONSTRAINT [FK_PurchaseClient] FOREIGN KEY REFERENCES [User](ID),
	[Date] DATETIME NOT NULL,
	[StateId] INT NOT NULL CONSTRAINT [FK_PurchaseState] FOREIGN KEY REFERENCES [PurchaseState](ID)
)
