CREATE TABLE [dbo].[Stock]
(
	[Id] INT NOT NULL CONSTRAINT [PK_StockId] PRIMARY KEY IDENTITY(1,1),
	[ProductId] INT NOT NULL CONSTRAINT [FK_ProductStock] FOREIGN KEY REFERENCES [Product](ID),
	[StoreId] INT NOT NULL CONSTRAINT [FK_ProductStore] FOREIGN KEY REFERENCES [Store](ID)
)
